apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chatapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-chatapp
  template:
    metadata:
      labels:
        app: mongodb-chatapp
    spec:
      containers:
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password" 